<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo Mage::helper('aw_eventbooking')->__('Ticket View'); ?></title>
    <link href="<?php echo $this->getSkinUrl('aw_eventbooking/css/minimal.css') ?>" rel="stylesheet"/>
</head>
<body>
<?php echo $this->getChildHtml('content') ?>
</body>
</html>
