<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>DieCrema.de - Espresso und Maschinen</title>

    <!-- Framework CSS -->
    <link rel="stylesheet" href="style/reset.css" type="text/css" media="screen, projection">
    <link rel="stylesheet" href="style/print.css" type="text/css" media="print">
    <link rel="stylesheet" href="style/typography.css" type="text/css" media="print">
    <link rel="stylesheet" href="style/grid.css" type="text/css" media="screen, projection">
    <link rel="stylesheet" href="style/default.css" type="text/css" media="screen, projection">
    <!--[if lt IE 8]><link rel="stylesheet" href="style/ie.css" type="text/css" media="screen, projection"><![endif]-->

  </head>
  <body>

    <div class="container">
    	<div class="h12"></div>
    	<div id="header">
    		<div id="logoArea">
	    		<div id="logoArea1"><img src="image/logo.png" /></div>
	    		<div id="logoArea2">
	    			<div class="floatLeft">
	    				<p>
		    			<a href="#" >Einloggen</a> |
		    			<a href="#" >Registrieren</a> |
		    			<a href="#" >Kundenservice</a>
		    			</p>
		    			<p class="textAlignRight">
		    			0800 700 2354 00
		    			</p>
		    		</div>
		    		<div class="floatLeft w12">&nbsp;</div>
		    		<div class="floatLeft">
		    			<img src="image/bag.png" />
		    		</div>
		    		<div class="floatLeft w12">&nbsp;</div>
		    		<div class="floatLeft">
	    				<p>
		    			Gekauft (0)
		    			</p>
		    			<a class="textAlignRight">
		    			Warenkorb
		    			</a>
		    		</div>
	    		</div>
    		</div>
    	</div>
    	
  	    <div  id="searchArea" class="textAlignRight">
  			<div class="floatRight bgrndBrown">
  				<input class="textInputSearch" value="Produkt suchen..." type="text" name="search" />
  				<input class="btnSearch" type="submit" value="Suchen" />
  			</div>
  		</div>
    	
    	<div class="h12 clear"></div>
      
      	<div id="navArea">
      		<ul>
      		<li><a>Espresso Maschinen</a></li>
      		<li><a>Mühlen</a></li>
      		<li><a>Zubehör</a></li>
      		<li><a>Kaffee</a></li>
      		<li><a>Angebote</a></li>
      		<li><a>Startseite</a></li>
      		</ul>
      	</div>
      	
      	<div id="posterArea" class="overflowHidden">
      		<div id="posterBox" style='float:left; background: url("image/giulia_espresso_maschine.png") 
      					no-repeat left top;' >
      		</div>
      		<div id="posterBoxGroup">
      			<div class="posterBoxSmall">
      				<div class="posterBoxImgBox" 
      					 style='background: url("image/giulia_espresso_maschine_sm.png") 
      					no-repeat center;'>
      					
      				</div>
      			</div>
      			<div class="posterBoxSmall">
      				<div class="posterBoxImgBox" 
      					style='background: url("image/mahlkoenig_vario_ii_kaffeemuehle_v2.png") 
      					no-repeat 48px center;'>
      					
      				</div>
      			</div>
      			<div class="posterBoxSmall posterBoxSmallLast">
      				<div style='background: url("skin/frontend/diecrema/default/images/posterBoxSmalllineH.png") 
      					no-repeat left top;'>
      					
      				</div>
      			</div>
     		</div>
      	</div>
      	
      	<div class="h24 clear"></div>
      	
      	<!-- New area -->
      	<div id="newArea" class="clear" >
      		<div class="floatLeft w48">&nbsp;</div>
      		
      		<div class="floatLeft w864">
      			<div id="newBoxHeader">
      				<div class="floatLeft w36">&nbsp;</div>
      				<div class="newBoxTab bgrndCoffeeBrown">Neuigkeiten</div>
      			</div>
      			
      			<div id="newBoxBorder" class="bgrndCoffeeBrown">
      				<div id="newBoxContent">
      				
      					<div class="h24">&nbsp;</div>
      					
      					<div class="newBoxRow">
	      					<div class="floatLeft w24">&nbsp;</div>
	      					
	      					<div id="newBoxProduct1" class="floatLeft w396">
	      						<div class="floatLeft">
	      							<img src="image/mahlkoenig_vario_ii_kaffeemuehle_sm.png" />
	      						</div>
	      						
	      						<div class="floatLeft w24">&nbsp;</div>
	      						
	      						<div class="floatLeft">
	      							<p>
	      							<a href="">Mahlkönig Vario II Kaffeemühle (V2)</a>
	      							</p>
	      							<p>
	      							<a href="">nur 444,00 EUR</a>
	      							</p>
	      							<p>
	      							<a href="">In den Warenkorb</a>
	      							</p>
	      						</div>	
	      					</div>
	      					
	      					<div class="floatLeft w24">&nbsp;</div>
	      					
	      					<div id="newBoxProduct2" class="floatLeft w396">
	      						<div class="floatLeft">
	      							<img src="image/mahlkoenig_vario_ii_kaffeemuehle_sm.png" />
	      						</div>
	      						
	      						<div class="floatLeft w24">&nbsp;</div>
	      						
	      						<div class="floatLeft">
	      							<p>
	      							<a href="">Mahlkönig Vario II Kaffeemühle (V2)</a>
	      							</p>
	      							<p>
	      							<a href="">nur 444,00 EUR</a>
	      							</p>
	      							<p>
	      							<a href="">In den Warenkorb</a>
	      							</p>
	      						</div>	
	      					</div>
	      					
	      					<div class="floatLeft w24">&nbsp;</div>
      					</div>
      					
      					<div class="newBoxRowSep">
	      					<div class="floatLeft w24">&nbsp;</div>
	      					
	      					<div id="newBoxSep1" class="newBoxSep floatLeft w396 h12">
	      						<img src="image/line_new_area.png" />
	      					</div>
	      					
	      					<div class="floatLeft w24">&nbsp;</div>
	      					
	      					<div id="newBoxSep2" class="newBoxSep floatLeft w396 h12">
	      						<img src="image/line_new_area.png" />
	      					</div>
	      					
	      					<div class="floatLeft w24">&nbsp;</div>
      					</div>
      					
      					<div class="newBoxRow">
	      					<div class="floatLeft w24">&nbsp;</div>
	      					
	      					<div id="newBoxProduct1" class="floatLeft w396">
	      						<div class="floatLeft">
	      							<img src="image/mahlkoenig_vario_ii_kaffeemuehle_sm.png" />
	      						</div>
	      						
	      						<div class="floatLeft w24">&nbsp;</div>
	      						
	      						<div class="floatLeft">
	      							<p>
	      							<a href="">Mahlkönig Vario II Kaffeemühle (V2)</a>
	      							</p>
	      							<p>
	      							<a href="">nur 444,00 EUR</a>
	      							</p>
	      							<p>
	      							<a href="">In den Warenkorb</a>
	      							</p>
	      						</div>	
	      					</div>
	      					
	      					<div class="floatLeft w24">&nbsp;</div>
	      					
	      					<div id="newBoxProduct2" class="floatLeft w396">
	      						<div class="floatLeft">
	      							<img src="image/mahlkoenig_vario_ii_kaffeemuehle_sm.png" />
	      						</div>
	      						
	      						<div class="floatLeft w24">&nbsp;</div>
	      						
	      						<div class="floatLeft">
	      							<p>
	      							<a href="">Mahlkönig Vario II Kaffeemühle (V2)</a>
	      							</p>
	      							<p>
	      							<a href="">nur 444,00 EUR</a>
	      							</p>
	      							<p>
	      							<a href="">In den Warenkorb</a>
	      							</p>
	      						</div>	
	      					</div>
	      					
	      					<div class="floatLeft w24">&nbsp;</div>
      					</div>
      				</div>
      			</div>
      		</div>
      	</div>
      	<!-- End: New area -->
      	
      	<div class="h24"></div>
      	
      	<!-- Footer -->
      	<div id="footer" class="bgrndCoffeeBrown">
      		<div class="h24 clearBoth"></div>
      		
      		<div class="floatLeft w60">&nbsp;</div>
      		<div id="newsletterBox" class="floatLeft w264">
      			<h1>Newsletter</h1>
      			<p>
      			<input class="w216" type="text" name="newsletter" />
      			</p>
      			
      			<p>
      			<a class="btnBrown">Absenden</a>
      			</p>
      		</div>
      		
      		<div class="floatLeft w24 h168 textAlignCenter">
      			<img src="image/line_footer.png" />
      		</div>
      		
      		<div id="serviceBox" class="floatLeft w264">
      			<h1>Service</h1>
      			<p><a href="">Über uns</a></p>
      			<p><a href="">Kontakt</a></p>
      			<p><a href="">Kundendienst Hotline</a></p>
      			<p><a href="">Werkstattservice</a></p>
      			<p><a href="">Garantie & Gewährleistung</a></p>
      		</div>
      		
      		
      		<div class="floatLeft w24 textAlignCenter">
      			<img src="image/line_footer.png" />
      		</div>
      		
      		<div id="infoBox" class="floatLeft w264">
      			<h1>Info</h1>
      			<p><a href="">Über uns</a></p>
      			<p><a href="">Kontakt</a></p>
      			<p><a href="">Kundendienst Hotline</a></p>
      			<p><a href="">Werkstattservice</a></p>
      			<p><a href="">Garantie & Gewährleistung</a></p>
      			
      		</div>
      		
      		<div class="floatLeft w60">&nbsp;</div>
      		
      		<div class="h24 clearBoth"></div>
      	</div>
      	<!-- End: Footer -->
      	
      	<div class="h12"></div>
    </div>
  </body>
</html>
