<?php
	$meigee_unique_general = MAGE::helper('ThemeOptionsUnique')->getThemeOptionsUnique('meigee_unique_general');
	$contactMap = $meigee_unique_general['contactmap']['map'];
	$contactMapApi = $meigee_unique_general['contactmap']['google_api']; 
	$contactMapLat = $meigee_unique_general['contactmap']['latitude'];
	$contactMapLong = $meigee_unique_general['contactmap']['longitude'];
	$contactMapZoom = $meigee_unique_general['contactmap']['mapzoom'];
	$contactMapType = $meigee_unique_general['contactmap']['maptype'];
	$contactMapMarker = $meigee_unique_general['contactmap']['marker'];
	$contactMarkerTitle = $meigee_unique_general['contactmap']['markertitle'];
	$contactBlock = $meigee_unique_general['contactmap']['block'];
	$contactBlockStatic = $meigee_unique_general['contactmap']['blockstatic'];
	$contactBlockWidth = $meigee_unique_general['contactmap']['blockwidth'];
	$contactBlockHeight = $meigee_unique_general['contactmap']['blockheight'];
	$contactBlockPosition = $meigee_unique_general['contactmap']['blockposition'];
	$random = rand(5, 1500);
?>
<?php if($contactMap): ?>
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js<?php if($contactMapApi){ ?>?key=<?php echo $contactMapApi; } ?>"></script>
	<div class="map-container">
		<?php if($contactBlock): ?>
		<div class="map-block<?php echo ' '.$contactBlockPosition; ?>" style="width:<?php echo $contactBlockWidth; ?>px; height:<?php echo $contactBlockHeight; ?>px;">
			<div class="indent">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($contactBlockStatic)->toHtml() ?>
			</div>
		</div>
		<?php endif; ?>
		<div id="map_canvas_<?php echo $random; ?>" class="map-wrapper"></div>
	</div>
<?php endif; ?>

<script type="text/javascript">
	<?php if($contactMap): ?>
		function initialize_<?php echo $random; ?>(){
			var myLatlng = new google.maps.LatLng(<?php echo $contactMapLat;?>, <?php echo $contactMapLong;?>);
			var map_canvas = document.getElementById('map_canvas_<?php echo $random; ?>');
			var map_options = {
			  center: myLatlng,
			  zoom: <?php echo $contactMapZoom;?>,
			  mapTypeId: google.maps.MapTypeId.<?php echo $contactMapType;?>
			}
			var map_<?php echo $random; ?> = new google.maps.Map(map_canvas, map_options)
			
			<?php if($contactMapMarker): ?>
			var marker = new google.maps.Marker({
				position: myLatlng,
				map: map_<?php echo $random; ?>,
				title: '<?php echo $contactMarkerTitle; ?>'
			});
			<?php endif; ?>
		}
		google.maps.event.addDomListener(window, 'load', initialize_<?php echo $random; ?>);

		var sizeMarker = 0;
		var currentSize = jQuery(document.body).width();
		if(currentSize < 480){currentSize = 1;}
		if(currentSize > 479 && currentSize < 768){currentSize = 2;}
		if(currentSize > 767 && currentSize < 977){currentSize = 3;}
		if(currentSize > 1279){currentSize = 4;}

		jQuery(window).resize(function(){
			if (jQuery(document.body).width() < 480) {
				sizeMarker = 1;
			}
			if (jQuery(document.body).width() > 479 && jQuery(document.body).width() < 768) {
				sizeMarker = 2;
			}
			if (jQuery(document.body).width() > 767 && jQuery(document.body).width() < 977){
				sizeMarker = 3;
			}
			if (jQuery(document.body).width() > 1279){
				sizeMarker = 4;
			}
			if(currentSize != sizeMarker){
				initialize_<?php echo $random; ?>();
				currentSize = sizeMarker;
			}
		});
	<?php endif; ?>
</script>