<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<?php
echo $this->getDesignStyles();
$package = Mage::getDesign()->getPackageName();
$theme = Mage::getDesign()->getTheme('frontend');
$is_persistent = Mage::helper('opc')->isPersistentMember();
?>
<div class="opc-wrapper-opc design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">
	<div class="page-title">
		<h2 class="opc-title"><?php echo $this->__('Checkout')?></h2>
		<div class="subtitle">
			<?php if(!$is_persistent):?>
				<?php echo $this->getChildHtml('paypal.button')?>

				<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()):?>
					<?php echo $this->getChildHtml('login');?>
				<?php endif;?>
			   <div class="clear move-columns"></div>
			<?php else:?>
				<?php echo $this->getChildHtml('login');?>
			<?php endif;?>
		</div>
	</div>
	<div class="clear"></div>

<div <?php if($is_persistent):?>style="display:none !important;"<?php endif;?>>

    <div class="opc-col-left">
		<div class="indent">
			<form id="opc-address-form-billing" method="post">
				<?php echo $this->getChildHtml('billing')?>
			</form>
				
			<form id="opc-address-form-shipping" class="hidden" method="post">
			<?php echo $this->getChildHtml('shipping')?>
			</form>
		</div>
	</div>

    <div class="opc-col-center">
		<div class="indent">
		   <?php if (!$this->getOnepage()->getQuote()->isVirtual()):?>
			<div class="shipping-block">
				<div class="opc-block-title">
					<h3><?php echo $this->__('Shipping Method')?></h3>
				</div>
				<div id="shipping-block-methods">
					<?php echo $this->getChildHtml('shipping_method');//$this->_getShippingMethodsHtml();?>
				</div>
			</div>
			<?php endif;?>
			<div class="payment-block <?php if ($this->getOnepage()->getQuote()->isVirtual()):?>clear-margin<?php endif;?>">
				<div class="opc-block-title">
					<h3><?php echo $this->__('Payment Method')?></h3>
				</div>
				<?php echo $this->getChildHtml('payment')//$this->_getPaymentMethodsHtml();?>
			</div>
			<?php if(Mage::helper('opc')->isShowDiscount()):?>
			<div class="discount-block">
				<div class="opc-block-title">
					<h3><?php echo $this->__('Discount Codes')?><span class='fa expand_plus'></span></h3>
				</div>
				<?php echo $this->getChildhtml('coupon');?>
			</div>
			<?php endif;?>

			<?php if(Mage::helper('opc')->isShowComment()):?>
				<?php echo $this->getChildhtml('customer.comment');?>
			<?php endif;?>
		</div>
    </div>

    <div class="opc-col-right">
		<div class="indent">
			<?php echo $this->_getReviewHtml()?>
			<?php if (Mage::getConfig()->getModuleConfig('IWD_OnepageCheckoutSignature')->is('active', 'true')): ?>
				<div class="signature-block">
					<h3><?php echo $this->__('Signature')?><span class='fa expand_plus'></span></h3>
					<div  class="collapse-block hidden">
						<?php echo $this->getChildhtml('opcsignature');?>
					</div>
				</div>
			<?php endif;?>
			<?php echo $this->getChildHtml('agreements')?>
			<div class="opc-review-actions" id="checkout-review-submit">
				<?php echo $this->getChildHtml('opc.newsletters');?>
				<button type="button" title="<?php echo $this->__('Place Order Now') ?>" class="button btn-checkout opc-btn-checkout"><span><span><?php echo $this->__('Place Order Now') ?></span></span></button>
			</div>
			<div class="clear"></div>
		</div>
    </div>
    
</div>

</div>
<script>
	var vopc = '<?php echo Mage::getConfig()->getModuleConfig("IWD_Opc")->version;?>';
	IWD.OPC.Checkout.config = '<?php echo $this->getJsonConfig()?>';
	<?php if ($this->getOnepage()->getQuote()->isVirtual()):?>
	IWD.OPC.Checkout.isVirtual = true;
	<?php endif;?>
</script>

<div id="agree_error" style="display:none !important;"><?php echo $this->__('Please agree to all the terms and conditions before placing the order.');?></div>
<div id="pssm_msg" style="display:none !important;"><?php echo $this->__('Please specify shipping method.');?></div>
<div class="opc-ajax-loader">
	<div class="loader"></div>
</div>
<div class="opc-message-wrapper design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">
	
	<div class="opc-messages">
		<a class="close-message-wrapper"><i class="fa fa-close"></i></a>
		<div class="opc-message-container"></div>
		<div class="opc-messages-action"><button class="button"><span><span><?php echo $this->__('Close')?></span></span></button></div>
	</div>
</div>