<?php /** @var $this Mediotype_Ticket_Block_Adminhtml_Ticket_View_Info */ ?>
<?php $ticket = $this->getTicket(); ?>
<div class="box-left">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account">
                Ticket #<?php echo $ticket->getId();?>
            </h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><label><?php echo Mage::helper('mediotype_ticket')->__('Ticket #'); ?></label>
                    </td>
                    <td class="value"><strong><?php echo $ticket->getId(); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('mediotype_ticket')->__('Product Sku'); ?></label>
                    </td>
                    <td class="value"><strong><?php echo $ticket->getData("sku"); ?></strong></td>
                </tr>
                <tr>
                    <td class="label">
                        <label><?php echo Mage::helper('mediotype_ticket')->__('Date/Time Redeemed'); ?></label></td>
                    <td class="value"><strong><?php echo $ticket->getData("date_redeemed"); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('mediotype_ticket')->__('Redeemed By'); ?></label>
                    </td>
                    <td class="value"><strong><?php echo $ticket->getData("redeemed_by"); ?></strong></td>
                </tr>
                <?php if ($ticket->hasBeenRevoked()): ?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('mediotype_ticket')->__('Date/Time Revoked'); ?></label></td>
                    <td class="value"><strong><?php echo $ticket->getData('date_revoked'); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('mediotype_ticket')->__('Revoked By'); ?></label></td>
                    <td class="value"><strong><?php echo $ticket->getData('revoked_by'); ?></strong></td>
                </tr>
                <?php endif; ?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('mediotype_ticket')->__('Admin Scan Count'); ?></label></td>
                    <td class="value"><strong><?php echo $ticket->getData('admin_scancount'); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('mediotype_ticket')->__('User Scan Count'); ?></label></td>
                    <td class="value"><strong><?php echo $ticket->getData('user_scancount'); ?></strong></td>
                </tr>
            </table>
        </div>
    </div>
</div>