<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
$meigee_unique_general = MAGE::helper('ThemeOptionsUnique')->getThemeOptionsUnique('meigee_unique_general');
$footer_status = $meigee_unique_general['footer']['footer_status'];
$footer_static = $meigee_unique_general['footer']['footer_static'];
?>
<footer id="footer"<?php if($footer_status == 0){echo ' class="original"';}?>>
	<?php if($footer_status == 1): ?>
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($footer_static)->toHtml() ?>
	<?php else: ?>
		<div class="container_12">
			<div class="grid_12">
				<div class="footer-links">
					<?php echo $this->getChildHtml('cms_footer_links') ?>
					<?php echo $this->getChildHtml('footer_links') ?>
				</div>
				<?php if ($static_html = $this->getChildHtml('unique_sk3_original_footer_logo')): ?>
					<?php echo $static_html; ?>
				<?php endif; ?>
				<address><?php echo $this->getCopyright() ?></address>
				<?php echo $this->getChildHtml('store_switcher') ?>
				<div class="clear"></div>
			</div>
			<div class="clear"></div>
		</div>
	<?php endif; ?>
</footer>