<?php /* @var $this AW_Eventbooking_Block_Adminhtml_Catalog_Product_Edit_Tab_Eventbooking_Element */ ?>
<?php
$_element = $this->getElement();
$_note    = $_element->getNote();
$_trId    = $_element->getHtmlContainerId();
$_class   = $_element->getFieldsetHtmlClass();
?>
<?php if (!$_element->getNoDisplay()): ?>
    <tr<?php if($_trId): ?> id="<?php echo $_trId ?>"<?php endif; ?>>
        <?php if ($_element->getType()=='hidden'): ?>
            <td colspan="2" class="hidden"><?php echo trim($_element->getElementHtml()) ?></td>
        <?php else: ?>
            <td class="label<?php echo $_class ? " {$_class}-label" : ''?>"><?php echo trim($_element->getLabelHtml()) ?></td>
            <td class="<?php echo $_element->hasValueClass() ? $_element->getValueClass() : 'value' ?><?php echo $_class ? " {$_class}-value" : ''?>">
                <?php echo trim($_element->getElementHtml()) ?>
                <?php if ($_note): ?>
                    <p class="note<?php echo $_class ? " {$_class}-note" : ''?>" id="note_<?php echo $_element->getId()?>"><span><?php echo $_note ?></span></p>
                <?php endif ?>
            </td>
            <?php if ($this->canDisplayUseDefault()): ?>
                <td class="value use-default">
                    <input type="checkbox" name="event[event_data][default][]" id="<?php echo $_element->getHtmlId() ?>_default"<?php if ($this->usedDefault()): ?> checked="checked"<?php endif; ?> onclick="toggleValueElements(this, this.parentNode.parentNode)" value="<?php echo $_element->getHtmlId(); ?>"/>
                    <label for="<?php echo $_element->getHtmlId() ?>_default" class="normal"><?php echo $this->__('Use Default Value') ?></label>
                </td>
            <?php endif; ?>
        <?php endif; ?>
    </tr>
<?php endif; ?>