<?php

function showCatsR($subcategories, $parentdArr, $currentCategory)
{
    $html = '';
    if ($subcategories &&  count($subcategories) > 0)
    {
        $_helper = Mage::helper('catalog/category');
        $html .= '<ul class="closed-default">';
        foreach($subcategories as $_subcategory)
        {
            $currentClass = $currentCategory->getId() == $_subcategory->getId() ? 'current' : '';
            $childrenCategories = $_subcategory->getChildrenCategories();
			
			$classBefore = 'class="';
			$classAfter = '"';
			$isParent = '';
			$isParent = 'parent ';
			$res = showCatsR($childrenCategories, $parentdArr, $currentCategory);
			if(empty($res)){
				$isParent = '';
			}
			if($currentClass == '' and $isParent == ''){
				$classBefore = '';
				$classAfter = '';
			}
            $html .= '<li '.$classBefore.$isParent.$currentClass.$classAfter.'> <a href="'.$_helper->getCategoryUrl($_subcategory).'">'.$_subcategory->getName() .'</a>';
            if (isset($parentdArr[$_subcategory->getId()]))
            {
                $html .= $res;
            }
            $html .= '</li>';
        }
        $html .= '</ul>';
    }
    return $html;
}




$_helper = Mage::helper('catalog/category');
$_categories = $_helper->getStoreCategories();
$currentCategory = Mage::registry('current_category');
$meigee_unique_sidebar = MAGE::helper('ThemeOptionsUnique')->getThemeOptionsUnique('meigee_unique_sidebar');
$block_categories = $meigee_unique_sidebar['block_categories'];
$routeName = Mage::app()->getRequest()->getRouteName();
$bodyClasses = $this->getLayout()->getBlock('root')->getBodyClass();
$isCmsPage = strpos($bodyClasses, 'cms-page-view');

if($routeName != 'blog' and !$isCmsPage) {
    $parentdArr = array_flip(explode('/', $currentCategory->getPath()));
}

?>
<?php if ($block_categories['option_2'] == 1 and !$isCmsPage){ ?>
    <div class="block block-vertical-nav">
        <?php if (count($_categories) > 0): ?>
            <?php foreach($_categories as $_category):
                if (isset($parentdArr[$_category->getId()])):

                    $_category = Mage::getModel('catalog/category')->load($_category->getId());
                    $_subcategories = $_category->getChildrenCategories() ?>
                        <div class="block-title">
                            <strong><span><?php echo $_category->getName() ?></span></strong>
                        </div>
                    <?php if (count($_subcategories) > 0) {?>
                        <?php if ($block_categories['option'] == 1){ ?>
                          <ul class="closed-default"  id="categories-accordion" >
                                <?php
                                $_menu = $this->renderCategoriesMenuHtml(0,'level-top');
                                if($_menu)
                                    {
                                        echo $_menu;
                                    }
                                 ?>
                            </ul>
                        <?php } else { ?>
                            <div class="block-content">
                                <?php echo showCatsR($_subcategories, $parentdArr, $currentCategory); ?>
                            </div>
                        <?php  } ?>
                    <?php } ?>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
<?php } ?>
