<div class="comment-block">
	<div class="opc-block-title">
		<h3><?php echo $this->__('Comment')?><span class='fa expand_plus'></span></h3>
	</div>
	<form autocomplete="off">
		<div class="comment">
			<div class="comment-form">
				<div class="input-box">
					<textarea class="input-text" id="customer_comment" name="customer_comment"></textarea>
				</div>	            
			</div>
		</div>
	</form>
</div>