<?php /** @var $this Mediotype_Ticket_Block_Print_View */
/** @var $event Mage_Catalog_Model_Product */
$horizontal = true;
$event = $this->getEvent();
?>
<?php foreach ($this->getOtickets() as $ticketOrderModel): ?>
    <?php /** @var $ticketOrderModel Mediotype_Ticket_Model_Order */ ?>
    <?php /** @var $typeModel Mediotype_Ticket_Model_Product_Type_Simpleticket */ ?>
    <?php $typeModel = $event->getTypeInstance() ?>
    <table style="margin: 15px auto 25px; border: 1px solid #a9a9a9">
        <tr>
            <td style="padding: 5px; text-align: left">
                <img style="text-align:left"
                     src="<?php echo $ticketOrderModel->getQrcodeUrl(); ?>"
                     alt="<?php echo $event->getEventTitle() ?>"/>
            </td>
            <td style="text-align:right; padding: 15px 5px; border-left: 1px solid #eee;">
                <table style=" margin: 0; min-width:300px; max-width:600px; border: none">
                    <tr>
                        <td colspan="2"
                            style="text-align:right">
                            <h1><?php echo $event->getEventTitle() ?></h1>

                            <p><?php echo $event->getEventSubtitle() ?></p>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 5px; text-align: left">
                        </td>
                        <td style="text-align:right; padding: 15px 5px;">
                            <p><?php echo $this->__('DATE') ?>
                                <br/><?php echo $typeModel->getFormatDateTime('F jS') ?>
                            </p>
                        </td>
                    </tr>
                    <?php $location = $event->getVenueName() ?>
                    <?php if ($location): ?>
                        <tr>
                            <td style="padding: 5px; text-align: left"
                                colspan="2">
                                <p style="text-align:left"><?php echo $this->__('Location') ?>
                                    <br/><?php echo $location ?></p>
                            </td>
                        </tr>
                    <?php endif; ?>
                    <tr>
                        <td style="padding: 5px; text-align: left">
                            <p><?php echo $this->__('TIME') ?>
                                <br/><?php echo $typeModel->getFormatDateTime('g:i A') ?>
                            </p>
                        </td>
                        <?php $phone = $event->getVenuePhone() ?>
                        <?php if ($phone): ?>
                            <td style="text-align:right; padding: 15px 5px;">
                                <p><?php echo $this->__('CONTACT') ?><br/><?php echo $phone ?></p>
                            </td>
                        <?php else: ?>
                            <td>&nbsp;</td>
                        <?php endif; ?>
                    </tr>
                </table>
                <?php ?>
            </td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center; border-top: 1px solid #eee"><?= $ticketOrderModel->getBarcodeHtml(); ?></td>
        </tr>
    </table>
<?php endforeach; ?>