<?php /** @var $this Mage_Adminhtml_Block_Sales_Order_View_Info */ ?>
<?php $_order = $this->getOrder() ?>
<?php
$orderAdminDate = $this->formatDate($_order->getCreatedAtDate(), 'medium', true);
$orderStoreDate = $this->formatDate($_order->getCreatedAtStoreDate(), 'medium', true);
?>
<!--Order Information-->
<div class="box-wide">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account">
                <?php echo Mage::helper('sales')->__('Order # %s', $_order->getRealOrderId()) ?>
            </h4>
        </div>
    </div>
</div>
<div class="clear"></div>
<div class="box-left">
    <!--Account Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Account Information') ?></h4>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('sales')->__('Customer Name') ?></label></td>
                        <td class="value">
                            <?php if ($_customerUrl = $this->getCustomerViewUrl()) : ?>
                                <a href="<?php echo $_customerUrl ?>"
                                   target="_blank"><strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong></a>
                            <?php else: ?>
                                <strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('sales')->__('Email') ?></label></td>
                        <td class="value"><a
                                href="mailto:<?php echo $_order->getCustomerEmail() ?>"><strong><?php echo $_order->getCustomerEmail() ?></strong></a>
                        </td>
                    </tr>
                    <?php foreach ($this->getCustomerAccountData() as $data): ?>
                        <tr>
                            <td class="label"><label><?php echo $data['label'] ?></label></td>
                            <td class="value"><strong><?php echo $data['value'] ?></strong></td>
                        </tr>
                    <?php endforeach;?>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="box-right">
    <!--Billing Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-billing-address"><?php echo Mage::helper('sales')->__('Billing Address') ?></h4>
        </div>
        <fieldset>
            <address><?php echo $_order->getBillingAddress()->getFormated(true) ?></address>
        </fieldset>
    </div>
</div>
<div class="clear"></div>
<hr/>