<<table>
	<tr>
        <td bgcolor="#EAEAEA" align="center" style="background:#EAEAEA; text-align:center;">
        	<center>
        		<p style="font-size:12px; margin:0;">
                    Bolingo UG (hb)<br/>
                    Sitz: Rosenthaler Straße 72a, 10119 Berlin<br/>
                    Handelsregisternummer: HRB 177102<br/>
                    Registergericht:: Berlin (Charlottenburg)<br/>
                    Geschäftsführer: Edgar Bongkishiy (Dipl. Ing (FH))
        		</p>
        	</center>
        </td>
    </tr>
</table>