<<table>
	<tr>
        <td bgcolor="#EAEAEA" align="center" style="background:#EAEAEA; text-align:center;">
        	<center>
        		<p style="font-size:12px; margin:0;">
        	DieCrema - Svenja Koch, Markus Schollmayer und Jens Koch GbR <br/>
            Löwenburgstr. 14 <br/>
            53604 Bad Honnef - Rhöndorf <br/><br/>
            
            Tel 0049-(0)2224-9898873 <br/>
            Fax 0049-(0)2224-9898874 <br/>
            E-Mail: info@diecrema.de <br/><br/>
            
            USt-IdNr. DE 815273136
        		</p>
        	</center>
        </td>
    </tr>
</table>