<?php if (!Mage::registry('current_category')) return ?>
<?php $_categories = $this->getCurrentChildCategories() ?>
<?php $_count = is_array($_categories)?count($_categories):$_categories->count(); ?>
<?php if($_count): ?>
<?php foreach ($_categories as $_category): ?>
<?php if($_category->getIsActive()): ?>
<div style="border: 1px solid red;padding: 10px; ">
	<a href="<?php echo $this->getCategoryUrl($_category) ?>"><?php echo $this->htmlEscape($_category->getName()) ?></a>
</div>
<?php endif; ?>
<?php endforeach ?>
<?php endif; ?>